name: flask-alchemy
channels:
  - defaults
  - conda-forge
dependencies:
  - aniso8601=4.0.1=py_0
  - appdirs=1.4.3=py_1
  - asn1crypto=0.24.0=py37_1003
  - attrs=18.2.0=py_0
  - black=18.9b0=py_0
  - cffi=1.11.5=py37h5e8e0c9_1
  - flask-jwt-extended=3.13.1=py_0
  - flask-restful=0.3.6=py_1
  - idna=2.7=py37_1002
  - pycparser=2.19=py_0
  - pycrypto=2.6.1=py37h470a237_2
  - pyjwt=1.6.4=py_0
  - pylint-flask=0.5=py_1
  - pylint-plugin-utils=0.4=py_0
  - python-dateutil=2.7.5=py_0
  - pytz=2018.7=py_0
  - six=1.11.0=py37_1001
  - toml=0.10.0=py_0
  - astroid=2.0.4=py37_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.10.15=py37_0
  - click=7.0=py37_0
  - cryptography=2.4.1=py37ha12b0ac_0
  - flask=1.0.2=py37_1
  - flask-sqlalchemy=2.3.2=py37_0
  - isort=4.3.4=py37_0
  - itsdangerous=1.1.0=py37_0
  - jinja2=2.10=py37_0
  - lazy-object-proxy=1.3.1=py37h1de35cc_2
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20170329=hb402a30_2
  - libffi=3.2.1=h475c297_4
  - logilab-common=1.4.2=py37_0
  - markupsafe=1.1.0=py37h1de35cc_0
  - mccabe=0.6.1=py37_1
  - ncurses=6.1=h0a44026_0
  - openssl=1.1.1a=h1de35cc_0
  - pip=18.1=py37_0
  - pylint=2.1.1=py37_0
  - python=3.7.1=haf84260_3
  - readline=7.0=h1de35cc_5
  - setuptools=40.6.2=py37_0
  - sqlalchemy=1.2.14=py37h1de35cc_0
  - sqlite=3.25.3=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - werkzeug=0.14.1=py37_0
  - wheel=0.32.3=py37_0
  - wrapt=1.10.11=py37h1de35cc_2
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - pep8==1.7.1
prefix: /Users/Elyalamillo/miniconda3/envs/flask-alchemy

